//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCaseApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeInReport
    {
        public int Id { get; set; }
        public double PointX { get; set; }
        public double PointY { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual Attribute Origin { get; set; }
    }
}
