//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowCaseApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetaDataDBContainer : DbContext
    {
        public MetaDataDBContainer()
            : base("name=MetaDataDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table> TableSet { get; set; }
        public virtual DbSet<Attribute> AttributeSet { get; set; }
        public virtual DbSet<View> ViewSet { get; set; }
        public virtual DbSet<Report> ReportSet { get; set; }
        public virtual DbSet<Query> QuerySet { get; set; }
    }
}
